/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: JointCommand.idl
  Source: JointCommand.hpp
  Cyclone DDS: v0.10.4

*****************************************************************/
#ifndef DDSCXX_JOINTCOMMAND_HPP
#define DDSCXX_JOINTCOMMAND_HPP

#include <cstdint>
#include <array>

namespace JointCommand
{
class Cmd
{
private:
 float q_ = 0.0f;
 float dq_ = 0.0f;
 float tau_ = 0.0f;
 float kp_ = 0.0f;
 float kd_ = 0.0f;

public:
  Cmd() = default;

  explicit Cmd(
    float q,
    float dq,
    float tau,
    float kp,
    float kd) :
    q_(q),
    dq_(dq),
    tau_(tau),
    kp_(kp),
    kd_(kd) { }

  float q() const { return this->q_; }
  float& q() { return this->q_; }
  void q(float _val_) { this->q_ = _val_; }
  float dq() const { return this->dq_; }
  float& dq() { return this->dq_; }
  void dq(float _val_) { this->dq_ = _val_; }
  float tau() const { return this->tau_; }
  float& tau() { return this->tau_; }
  void tau(float _val_) { this->tau_ = _val_; }
  float kp() const { return this->kp_; }
  float& kp() { return this->kp_; }
  void kp(float _val_) { this->kp_ = _val_; }
  float kd() const { return this->kd_; }
  float& kd() { return this->kd_; }
  void kd(float _val_) { this->kd_ = _val_; }

  bool operator==(const Cmd& _other) const
  {
    (void) _other;
    return q_ == _other.q_ &&
      dq_ == _other.dq_ &&
      tau_ == _other.tau_ &&
      kp_ == _other.kp_ &&
      kd_ == _other.kd_;
  }

  bool operator!=(const Cmd& _other) const
  {
    return !(*this == _other);
  }

};

class JointCmd
{
private:
 int32_t id_ = 0;
 uint64_t sequence_frame_ = 0;
 uint64_t timestamp_ = 0;
 int32_t num_ = 0;
 std::array<::JointCommand::Cmd, 16> cmd_ = { };

public:
  JointCmd() = default;

  explicit JointCmd(
    int32_t id,
    uint64_t sequence_frame,
    uint64_t timestamp,
    int32_t num,
    const std::array<::JointCommand::Cmd, 16>& cmd) :
    id_(id),
    sequence_frame_(sequence_frame),
    timestamp_(timestamp),
    num_(num),
    cmd_(cmd) { }

  int32_t id() const { return this->id_; }
  int32_t& id() { return this->id_; }
  void id(int32_t _val_) { this->id_ = _val_; }
  uint64_t sequence_frame() const { return this->sequence_frame_; }
  uint64_t& sequence_frame() { return this->sequence_frame_; }
  void sequence_frame(uint64_t _val_) { this->sequence_frame_ = _val_; }
  uint64_t timestamp() const { return this->timestamp_; }
  uint64_t& timestamp() { return this->timestamp_; }
  void timestamp(uint64_t _val_) { this->timestamp_ = _val_; }
  int32_t num() const { return this->num_; }
  int32_t& num() { return this->num_; }
  void num(int32_t _val_) { this->num_ = _val_; }
  const std::array<::JointCommand::Cmd, 16>& cmd() const { return this->cmd_; }
  std::array<::JointCommand::Cmd, 16>& cmd() { return this->cmd_; }
  void cmd(const std::array<::JointCommand::Cmd, 16>& _val_) { this->cmd_ = _val_; }
  void cmd(std::array<::JointCommand::Cmd, 16>&& _val_) { this->cmd_ = _val_; }

  bool operator==(const JointCmd& _other) const
  {
    (void) _other;
    return id_ == _other.id_ &&
      sequence_frame_ == _other.sequence_frame_ &&
      timestamp_ == _other.timestamp_ &&
      num_ == _other.num_ &&
      cmd_ == _other.cmd_;
  }

  bool operator!=(const JointCmd& _other) const
  {
    return !(*this == _other);
  }

};

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::JointCommand::Cmd>::getTypeName()
{
  return "JointCommand::Cmd";
}

template <> constexpr bool TopicTraits<::JointCommand::Cmd>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::JointCommand::Cmd>::type_map_blob_sz() { return 354; }
template<> constexpr unsigned int TopicTraits<::JointCommand::Cmd>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::JointCommand::Cmd>::type_map_blob() {
  static const uint8_t blob[] = {
 0x7b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0x69,  0x7a,  0x4e,  0xfd,  0x31,  0x51,  0xd3, 
 0x5d,  0xbd,  0xfb,  0x32,  0x0c,  0x7d,  0xd9,  0x00,  0x63,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x53,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x76,  0x94,  0xf4,  0xa6,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x47,  0xbc,  0xdc,  0xd7,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x45,  0x80,  0xc2,  0x74,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x26,  0xb5,  0x68,  0xe4,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x87,  0x22,  0x16,  0x52,  0x00, 
 0xb5,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x5a,  0x2a,  0x57,  0x29,  0x57,  0xe8,  0x70, 
 0xd8,  0x24,  0x91,  0x7b,  0x40,  0xb9,  0x66,  0x00,  0x9d,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x1a,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x12,  0x00,  0x00,  0x00,  0x4a,  0x6f,  0x69,  0x6e, 
 0x74,  0x43,  0x6f,  0x6d,  0x6d,  0x61,  0x6e,  0x64,  0x3a,  0x3a,  0x43,  0x6d,  0x64,  0x00,  0x00,  0x00, 
 0x75,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x10,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x09,  0x00,  0x02,  0x00,  0x00,  0x00,  0x71,  0x00,  0x00,  0x00,  0x11,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x03,  0x00,  0x00,  0x00,  0x64,  0x71,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x12,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00, 
 0x04,  0x00,  0x00,  0x00,  0x74,  0x61,  0x75,  0x00,  0x00,  0x00,  0x00,  0x00,  0x11,  0x00,  0x00,  0x00, 
 0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x03,  0x00,  0x00,  0x00,  0x6b,  0x70,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x11,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00, 
 0x03,  0x00,  0x00,  0x00,  0x6b,  0x64,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0xf2,  0x5a,  0x2a,  0x57,  0x29,  0x57,  0xe8,  0x70,  0xd8,  0x24,  0x91,  0x7b, 
 0x40,  0xb9,  0x66,  0xf1,  0x69,  0x7a,  0x4e,  0xfd,  0x31,  0x51,  0xd3,  0x5d,  0xbd,  0xfb,  0x32,  0x0c, 
 0x7d,  0xd9, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::JointCommand::Cmd>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0x69,  0x7a,  0x4e,  0xfd,  0x31,  0x51,  0xd3,  0x5d,  0xbd,  0xfb,  0x32, 
 0x0c,  0x7d,  0xd9,  0x00,  0x67,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x5a,  0x2a,  0x57,  0x29,  0x57,  0xe8,  0x70,  0xd8,  0x24,  0x91,  0x7b, 
 0x40,  0xb9,  0x66,  0x00,  0xa1,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

template <> constexpr const char* TopicTraits<::JointCommand::JointCmd>::getTypeName()
{
  return "JointCommand::JointCmd";
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::JointCommand::JointCmd>::type_map_blob_sz() { return 756; }
template<> constexpr unsigned int TopicTraits<::JointCommand::JointCmd>::type_info_blob_sz() { return 148; }
template<> inline const uint8_t * TopicTraits<::JointCommand::JointCmd>::type_map_blob() {
  static const uint8_t blob[] = {
 0x0b,  0x01,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0xf1,  0xaa,  0x5d,  0xfd,  0x8d,  0x8e,  0xc3,  0x08, 
 0x51,  0x26,  0x9c,  0xba,  0xd1,  0x4d,  0x16,  0x00,  0x7c,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x6c,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x31,  0x00,  0x04,  0xb8,  0x0b,  0xb7,  0x74,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x08,  0xef,  0xd2,  0x68,  0xec,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x08,  0xd7,  0xe6,  0xd5,  0x5b,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x04,  0x0f,  0xc3,  0xcf,  0xbc,  0x00, 
 0x24,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x90,  0xf1,  0x01,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x10,  0xf1,  0x69,  0x7a,  0x4e,  0xfd,  0x31,  0x51,  0xd3,  0x5d,  0xbd,  0xfb, 
 0x32,  0x0c,  0x7d,  0xd9,  0xdf,  0xff,  0x0a,  0x7f,  0xf1,  0x69,  0x7a,  0x4e,  0xfd,  0x31,  0x51,  0xd3, 
 0x5d,  0xbd,  0xfb,  0x32,  0x0c,  0x7d,  0xd9,  0x00,  0x63,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x53,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x76,  0x94,  0xf4,  0xa6,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x47,  0xbc,  0xdc,  0xd7,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x45,  0x80,  0xc2,  0x74,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x26,  0xb5,  0x68,  0xe4,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x87,  0x22,  0x16,  0x52,  0x00, 
 0x99,  0x01,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0xf2,  0xa6,  0x4c,  0x3e,  0xcb,  0xe2,  0x0c,  0x3b, 
 0x70,  0x06,  0x7e,  0x7d,  0x5d,  0x96,  0x9a,  0x00,  0xce,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x1f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x17,  0x00,  0x00,  0x00,  0x4a,  0x6f,  0x69,  0x6e, 
 0x74,  0x43,  0x6f,  0x6d,  0x6d,  0x61,  0x6e,  0x64,  0x3a,  0x3a,  0x4a,  0x6f,  0x69,  0x6e,  0x74,  0x43, 
 0x6d,  0x64,  0x00,  0x00,  0xa2,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x11,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x31,  0x00,  0x04,  0x00,  0x03,  0x00,  0x00,  0x00,  0x69,  0x64,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x1d,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x08,  0x00, 
 0x0f,  0x00,  0x00,  0x00,  0x73,  0x65,  0x71,  0x75,  0x65,  0x6e,  0x63,  0x65,  0x5f,  0x66,  0x72,  0x61, 
 0x6d,  0x65,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x18,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x08,  0x00,  0x0a,  0x00,  0x00,  0x00,  0x74,  0x69,  0x6d,  0x65,  0x73,  0x74,  0x61,  0x6d, 
 0x70,  0x00,  0x00,  0x00,  0x12,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x04,  0x00, 
 0x04,  0x00,  0x00,  0x00,  0x6e,  0x75,  0x6d,  0x00,  0x00,  0x00,  0x00,  0x00,  0x2a,  0x00,  0x00,  0x00, 
 0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x90,  0xf2,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x10,  0xf2,  0x5a,  0x2a,  0x57,  0x29,  0x57,  0xe8,  0x70,  0xd8,  0x24,  0x91,  0x7b,  0x40,  0xb9,  0x66, 
 0x04,  0x00,  0x00,  0x00,  0x63,  0x6d,  0x64,  0x00,  0x00,  0x00,  0xf2,  0x5a,  0x2a,  0x57,  0x29,  0x57, 
 0xe8,  0x70,  0xd8,  0x24,  0x91,  0x7b,  0x40,  0xb9,  0x66,  0x00,  0x00,  0x00,  0x9d,  0x00,  0x00,  0x00, 
 0xf2,  0x51,  0x01,  0x00,  0x1a,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x12,  0x00,  0x00,  0x00, 
 0x4a,  0x6f,  0x69,  0x6e,  0x74,  0x43,  0x6f,  0x6d,  0x6d,  0x61,  0x6e,  0x64,  0x3a,  0x3a,  0x43,  0x6d, 
 0x64,  0x00,  0x00,  0x00,  0x75,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x10,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x02,  0x00,  0x00,  0x00,  0x71,  0x00,  0x00,  0x00, 
 0x11,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x03,  0x00,  0x00,  0x00, 
 0x64,  0x71,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x12,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x09,  0x00,  0x04,  0x00,  0x00,  0x00,  0x74,  0x61,  0x75,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x11,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x03,  0x00,  0x00,  0x00, 
 0x6b,  0x70,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x11,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x09,  0x00,  0x03,  0x00,  0x00,  0x00,  0x6b,  0x64,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x40,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0xf2,  0xa6,  0x4c,  0x3e,  0xcb,  0xe2,  0x0c,  0x3b, 
 0x70,  0x06,  0x7e,  0x7d,  0x5d,  0x96,  0x9a,  0xf1,  0xaa,  0x5d,  0xfd,  0x8d,  0x8e,  0xc3,  0x08,  0x51, 
 0x26,  0x9c,  0xba,  0xd1,  0x4d,  0x16,  0xf2,  0x5a,  0x2a,  0x57,  0x29,  0x57,  0xe8,  0x70,  0xd8,  0x24, 
 0x91,  0x7b,  0x40,  0xb9,  0x66,  0xf1,  0x69,  0x7a,  0x4e,  0xfd,  0x31,  0x51,  0xd3,  0x5d,  0xbd,  0xfb, 
 0x32,  0x0c,  0x7d,  0xd9, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::JointCommand::JointCmd>::type_info_blob() {
  static const uint8_t blob[] = {
 0x90,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x40,  0x00,  0x00,  0x00,  0x3c,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0xaa,  0x5d,  0xfd,  0x8d,  0x8e,  0xc3,  0x08,  0x51,  0x26,  0x9c,  0xba, 
 0xd1,  0x4d,  0x16,  0x00,  0x80,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x1c,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00,  0xf1,  0x69,  0x7a,  0x4e,  0xfd,  0x31,  0x51,  0xd3, 
 0x5d,  0xbd,  0xfb,  0x32,  0x0c,  0x7d,  0xd9,  0x00,  0x67,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40, 
 0x40,  0x00,  0x00,  0x00,  0x3c,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00,  0xf2,  0xa6,  0x4c,  0x3e, 
 0xcb,  0xe2,  0x0c,  0x3b,  0x70,  0x06,  0x7e,  0x7d,  0x5d,  0x96,  0x9a,  0x00,  0xd2,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x1c,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00, 
 0xf2,  0x5a,  0x2a,  0x57,  0x29,  0x57,  0xe8,  0x70,  0xd8,  0x24,  0x91,  0x7b,  0x40,  0xb9,  0x66,  0x00, 
 0xa1,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::JointCommand::Cmd>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::JointCommand::Cmd>::getTypeName();
    }
};

template <>
struct topic_type_name<::JointCommand::JointCmd>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::JointCommand::JointCmd>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::JointCommand::Cmd)
REGISTER_TOPIC_TYPE(::JointCommand::JointCmd)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::JointCommand::Cmd>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::JointCommand::Cmd& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.q()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.dq()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.tau()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.kp()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.kd()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::JointCommand::Cmd& instance, bool as_key) {
  auto &props = get_type_props<::JointCommand::Cmd>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::JointCommand::Cmd& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.q()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.dq()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.tau()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.kp()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.kd()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::JointCommand::Cmd& instance, bool as_key) {
  auto &props = get_type_props<::JointCommand::Cmd>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::JointCommand::Cmd& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.q()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.dq()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.tau()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.kp()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.kd()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::JointCommand::Cmd& instance, bool as_key) {
  auto &props = get_type_props<::JointCommand::Cmd>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::JointCommand::Cmd& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.q()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.dq()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.tau()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.kp()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.kd()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::JointCommand::Cmd& instance, bool as_key) {
  auto &props = get_type_props<::JointCommand::Cmd>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

template<>
propvec &get_type_props<::JointCommand::JointCmd>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::JointCommand::JointCmd& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.id()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.sequence_frame()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.timestamp()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.num()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, false))
        return false;
      for (const auto & a_1:instance.cmd()) {  //array depth 1
      if (!write(streamer, a_1, prop))
        return false;
      }  //array depth 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::JointCommand::JointCmd& instance, bool as_key) {
  auto &props = get_type_props<::JointCommand::JointCmd>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::JointCommand::JointCmd& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.id()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.sequence_frame()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.timestamp()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.num()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, false))
        return false;
      for (auto & a_1:instance.cmd()) {  //array depth 1
      if (!read(streamer, a_1, prop))
        return false;
      }  //array depth 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::JointCommand::JointCmd& instance, bool as_key) {
  auto &props = get_type_props<::JointCommand::JointCmd>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::JointCommand::JointCmd& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.id()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.sequence_frame()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.timestamp()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.num()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, false))
        return false;
      for (const auto & a_1:instance.cmd()) {  //array depth 1
      if (!move(streamer, a_1, prop))
        return false;
      }  //array depth 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::JointCommand::JointCmd& instance, bool as_key) {
  auto &props = get_type_props<::JointCommand::JointCmd>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::JointCommand::JointCmd& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.id()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.sequence_frame()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.timestamp()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.num()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, false))
        return false;
      for (const auto & a_1:instance.cmd()) {  //array depth 1
      if (!max(streamer, a_1, prop))
        return false;
      }  //array depth 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::JointCommand::JointCmd& instance, bool as_key) {
  auto &props = get_type_props<::JointCommand::JointCmd>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_JOINTCOMMAND_HPP
